resolver: nightly-2024-01-05

extra-deps:
  - ghc-lib-parser-9.8.1.20231121
  - ghc-lib-parser-ex-9.8.0.0
  - test-framework-0.8.2.0
  - test-framework-hunit-0.3.0.2
  - ansi-wl-pprint-0.6.9

save-hackage-creds: false
compiler: ghc-9.8.1
