name: Cabal

on: ['pull_request', 'push']

jobs:
  build:
    name: Build on ${{ matrix.os }} GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ["9.0.2", "9.2.7", "9.4.4"]
      fail-fast: false

    steps:
    - name: Get the version
      id: get_version
      run: 'echo ::set-output name=version::${GITHUB_REF#refs/tags/}'

    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v2
      name: Setup Haskell Cabal
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal
      with:
        path: ~/.stack
        key: "${{ runner.os }}-${{ matrix.ghc }}-v9-${{ hashFiles('stylish-haskell.cabal') }}"

    - name: Build
      run: cabal build --enable-tests
      id: build

    - name: Test
      run: cabal test

    - name: Build artifact
      if: startsWith(github.ref, 'refs/tags')
      run: make artifact
      env:
        PATAT_TAG: ${{ steps.get_version.outputs.version }}

    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        path: artifacts/*
        name: artifacts

