name: Cabal

on: ['pull_request', 'push']

jobs:
  build:
    name: Build on ${{ matrix.os }} GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ["9.4", "9.6", "9.8", "9.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v2
      name: Setup Haskell Cabal
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal
      with:
        path: ~/.cabal
        key: "${{ runner.os }}-${{ matrix.ghc }}-v9-${{ hashFiles('stylish-haskell.cabal') }}"

    - name: Build
      run: cabal build
      id: build

    - name: Test
      run: cabal test

