name: CI

on: ['pull_request', 'push']

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        stack: ["2.15.7"]

    steps:
    - uses: actions/checkout@v2

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        enable-stack: true
        stack-version: ${{ matrix.stack }}
        stack-no-global: true

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: "${{ runner.os }}-v9-${{ hashFiles('stylish-haskell.cabal', 'stack.yaml', 'stack.yaml.lock') }}"

    - name: Add ~/.local/bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build
      run: make build
      id: build

    - name: Test
      run: make test

    - name: Build artifact
      if: startsWith(github.ref, 'refs/tags')
      run: make artifact

    - uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags')
      with:
        path: artifacts/*
        name: artifacts-${{ runner.os }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: artifacts-*

    - run: ls -R
    - run: 'sha256sum artifacts-*/*'

    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: 'artifacts-*/stylish-haskell-*'
